#no-dnd-shadow = false;
#no-dock-shadow = false;
#clear-shadow = false;
transition-length = 300
transition-pow-x = 0.1
transition-pow-y = 0.1
transition-pow-w = 0.1
transition-pow-h = 0.1
size-transition = true
shadow = true;
#corner-radius = 7;
#for rounded corners 
corner-radius = 12.0;
shadow-radius = 10;
shadow-offset-x = -9;
shadow-offset-y = -9;
shadow-opacity = 0.30;
shadow-red = 0.0;
shadow-green = 0.0;
shadow-blue = 0.0;
round-borders = 1;
shadow-exclude = [
     "name = 'stalonetray'",
     "name = 'polybar'",
     "name = 'plank'",
     "name = 'Notification'",
     "name = 'fluxbox'",
     "class_g = 'bspwm'",
     "class_i = 'presel_feedback'",
     "class_g = 'fluxbox'",
     "class_g = 'Notify-osd'",
     "class_g = 'xfce4-panel'",
     "class_i = 'POWERPNT.EXE'",
     "class_i = 'WINWORD.EXE'",
     "class_i = 'Meteo'"
];

shadow-ignore-shaped = false;
inactive-opacity = 1.0;
active-opacity = 1.0;
inactive-opacity-override = false;
opacity-rule = [
   "10:class_g = 'Bspwm'",
   "10:class_i = 'presel_feedback'"
];

wintypes :
{
    popup_menu =
    {
        opacity = 1.0;
    };
    dropdown_menu =
    {
        opacity = 1.0;
    };
    dnd =
    {
        shadow = false;
    };
    dock =
    {
        shadow = true;
    };
    tooltip =
    {
        fade = false;
        shadow = true;
        opacity = 1.0;
        focus = true;
    };
};

# Fading
fading = true;
fade-delta = 3;
fade-in-step = 0.03;
fade-out-step = 0.03;
fade-exclude = [
    "class_g = 'slop'"
];
frame-opacity = 1.0
inactive-opacity-override = false
active-opacity = 1.0
#inactive-opacity = 0.8
#rounded-corners-exclude = [
#  "class_g = 'dwm'",
#  "class_g = 'Polybar'",
#]
vsync = true
backend = "glx";
